spring:
  cache:
    type: redis
    redis:
      cache-null-values: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwtproject
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      host: localhost
      port: 27017
      database: socialnetwork  # Tên của cơ sở dữ liệu MongoDB mà bạn muốn kết nối


logging:
  level:
    org.springframework.security: trace
jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem